"""CPU adapter preparation changes for the pinned GLM SGLang image."""

SGLANG_GLM_LORA_LOADING_PATCH = (
    "--- a/python/sglang/srt/lora/lora.py\n"
    "+++ b/python/sglang/srt/lora/lora.py\n"
    "@@ -20,6 +20,8 @@\n"
    " \n"
    " import logging\n"
    " import re\n"
    "+from pathlib import Path\n"
    "+from safetensors import safe_open\n"
    " from typing import Dict, List, Optional\n"
    " \n"
    " import torch\n"
    "@@ -31,6 +33,7 @@\n"
    " from sglang.srt.lora.lora_config import LoRAConfig\n"
    " from sglang.srt.model_loader.loader import DefaultModelLoader\n"
    " from sglang.srt.utils.hf_transformers_utils import AutoConfig\n"
    "+from sglang.srt.lora.utils import get_normalized_target_modules\n"
    " \n"
    ' # Matches both per-expert keys ("...experts.0.<module>...") and shared-outer\n'
    ' # keys ("...experts.<module>..."), while excluding "shared_experts." (where the\n'
    "@@ -60,8 +63,10 @@\n"
    "         load_config: LoadConfig,\n"
    "         lora_backend: BaseLoRABackend,\n"
    "         base_model: Optional[torch.nn.Module] = None,\n"
    "+        expert_range: Optional[tuple[int, int]] = None,\n"
    "     ):\n"
    "         super().__init__()\n"
    "+        self.expert_range = expert_range\n"
    "         self.uid: str = uid\n"
    "         self.config: LoRAConfig = config\n"
    '         assert self.config.hf_config["peft_type"].lower() == "lora"\n'
    "@@ -142,6 +147,16 @@\n"
    " \n"
    "     def initialize_weights(self):\n"
    "         model_path = self.config.path\n"
    '+        local_file = Path(model_path) / "adapter_model.safetensors"\n'
    "+        if self.expert_range is not None and local_file.is_file():\n"
    '+            with safe_open(local_file, framework="pt", device="cpu") as weights:\n'
    "+                for name in weights.keys():\n"
    "+                    if self._owns_expert(name):\n"
    "+                        # Cached tensors must not retain the volume mmap.\n"
    "+                        # Later publications need to refresh this mount.\n"
    "+                        self._process_weight(name, weights.get_tensor(name).clone())\n"
    "+            self._normalize_weights()\n"
    "+            return\n"
    "         loader = DefaultModelLoader(self.load_config)\n"
    '         revision = getattr(self.config.hf_config, "revision", None)\n'
    " \n"
    "@@ -161,9 +176,15 @@\n"
    " \n"
    "         self._normalize_weights()\n"
    " \n"
    "+    def _owns_expert(self, name: str) -> bool:\n"
    '+        expert = re.search(r"\\.experts\\.(\\d+)\\.", name)\n'
    "+        return self.expert_range is None or expert is None or (\n"
    "+            self.expert_range[0] <= int(expert[1]) < self.expert_range[1]\n"
    "+        )\n"
    "+\n"
    "     def _process_weight(self, name: str, loaded_weight: torch.Tensor):\n"
    "-        from sglang.srt.lora.utils import get_normalized_target_modules\n"
    "-\n"
    "+        if not self._owns_expert(name):\n"
    "+            return\n"
    "         normalized_target_modules = get_normalized_target_modules(\n"
    "             self.config.target_modules\n"
    "         )\n"
    "--- a/python/sglang/srt/lora/lora_manager.py\n"
    "+++ b/python/sglang/srt/lora/lora_manager.py\n"
    "@@ -286,41 +286,53 @@\n"
    "         return result\n"
    " \n"
    "     def _load_lora_adapter(self, lora_ref: LoRARef) -> LoRAUpdateOutput:\n"
    '-        """\n'
    "-        Load a single LoRA adapter from the specified path.\n"
    "-\n"
    "-        Args:\n"
    "-            lora_ref (LoRARef): The LoRARef object containing the LoRA name, path, and ID.\n"
    '-        """\n'
    "-        assert lora_ref.lora_name is not None and lora_ref.lora_path is not None, (\n"
    '-            "LoRARef must have both lora_name and lora_path set for loading."\n'
    "-        )\n"
    "-        assert lora_ref.lora_id not in self.loras, (\n"
    '-            f"LoRA adapter with ID {lora_ref.lora_id} is already loaded. This should have been verified before request is sent to the backend."\n'
    "-        )\n"
    "-\n"
    "         try:\n"
    "-            # load configs\n"
    "-            new_adapter = LoRAConfig(\n"
    "-                lora_ref.lora_path,\n"
    "-                base_vocab_size=self.base_hf_config.vocab_size,\n"
    "-            )\n"
    "-            self.validate_new_adapter(new_adapter, lora_ref)\n"
    "-            self.configs[lora_ref.lora_id] = new_adapter\n"
    "-\n"
    "-            # load weights\n"
    "-            self.load_lora_weights(lora_ref)\n"
    "-\n"
    "-            # keep metadata for displayed messages\n"
    "-            self.lora_refs[lora_ref.lora_id] = lora_ref\n"
    "-            self.num_pinned_loras += int(lora_ref.pinned)\n"
    "-        except Exception as e:\n"
    "-            return self.create_lora_update_result(\n"
    "-                success=False,\n"
    "-                error_message=str(e),\n"
    "-            )\n"
    "-\n"
    "-        return self.create_lora_update_result(success=True)\n"
    "+            prepared = self.prepare_lora_adapter(lora_ref)\n"
    "+            return self.install_prepared_lora_adapter(lora_ref, prepared)\n"
    "+        except Exception as exc:\n"
    "+            return self.create_lora_update_result(False, str(exc))\n"
    "+\n"
    "+    def _make_lora_adapter(self, lora_ref, config):\n"
    '+        pool = getattr(self, "memory_pool", None)\n'
    "+        expert_range = None\n"
    "+        if pool is not None and pool.moe_use_local_expert_ids:\n"
    "+            first = pool.moe_ep_rank * pool._num_experts_local\n"
    "+            expert_range = (first, first + pool._num_experts_local)\n"
    "+        return LoRAAdapter(\n"
    "+            lora_ref.lora_id, config, self.base_hf_config, self.load_config,\n"
    "+            self.lora_backend, base_model=self.base_model, expert_range=expert_range,\n"
    "+        )\n"
    "+\n"
    "+    def prepare_lora_adapter(self, lora_ref):\n"
    '+        """Build CPU weights without changing the active registry or GPU buffers."""\n'
    "+        config = LoRAConfig(\n"
    "+            lora_ref.lora_path, base_vocab_size=self.base_hf_config.vocab_size\n"
    "+        )\n"
    "+        adapter = self._make_lora_adapter(lora_ref, config)\n"
    "+        adapter.initialize_weights()\n"
    "+        return config, adapter\n"
    "+\n"
    "+    def install_prepared_lora_adapter(self, lora_ref, prepared):\n"
    '+        """Called on the scheduler thread after every TP rank has prepared."""\n'
    "+        config, adapter = prepared\n"
    "+        self.validate_new_adapter(config, lora_ref)\n"
    "+        if lora_ref.lora_id in self.loras:\n"
    '+            raise ValueError(f"Adapter {lora_ref.lora_id} is already loaded")\n'
    "+        warn_if_adapter_targets_embeddings(\n"
    "+            lora_name=lora_ref.lora_name,\n"
    "+            embedding_layer_names=adapter.embedding_layers.keys(),\n"
    "+            speculative_algorithm=self.speculative_algorithm,\n"
    "+        )\n"
    "+        self.configs[lora_ref.lora_id] = config\n"
    "+        self.loras[lora_ref.lora_id] = adapter\n"
    "+        self.lora_refs[lora_ref.lora_id] = lora_ref\n"
    "+        self.num_pinned_loras += int(lora_ref.pinned)\n"
    "+        cpu_bytes = sum(\n"
    "+            tensor.numel() * tensor.element_size()\n"
    "+            for layer in adapter.layers for tensor in layer.weights.values()\n"
    "+        )\n"
    '+        logger.info("LoRA prepared id=%s cpu_bytes=%d", lora_ref.lora_id, cpu_bytes)\n'
    "+        return self.create_lora_update_result(True)\n"
    " \n"
    "     def validate_new_adapter(self, lora_config: LoRAConfig, lora_ref: LoRARef):\n"
    '         """\n'
    "@@ -901,13 +913,8 @@\n"
    '         """\n'
    "         Load the weights of a LoRA adapter to CPU memory and conducts post-loading validation.\n"
    '         """\n'
    "-        lora_adapter = LoRAAdapter(\n"
    "-            lora_ref.lora_id,\n"
    "-            self.configs[lora_ref.lora_id],\n"
    "-            self.base_hf_config,\n"
    "-            self.load_config,\n"
    "-            self.lora_backend,\n"
    "-            base_model=self.base_model,\n"
    "+        lora_adapter = self._make_lora_adapter(\n"
    "+            lora_ref, self.configs[lora_ref.lora_id]\n"
    "         )\n"
    "         lora_adapter.initialize_weights()\n"
    " \n"
    "@@ -925,13 +932,8 @@\n"
    '         """\n'
    "         Load the weights of a LoRA adapter from tensors to CPU memory.\n"
    '         """\n'
    "-        lora_adapter = LoRAAdapter(\n"
    "-            lora_ref.lora_id,\n"
    "-            self.configs[lora_ref.lora_id],\n"
    "-            self.base_hf_config,\n"
    "-            self.load_config,\n"
    "-            self.lora_backend,\n"
    "-            base_model=self.base_model,\n"
    "+        lora_adapter = self._make_lora_adapter(\n"
    "+            lora_ref, self.configs[lora_ref.lora_id]\n"
    "         )\n"
    "         lora_adapter.initialize_weights_from_tensors(tensors)\n"
    " \n"
    "--- a/python/sglang/srt/managers/scheduler.py\n"
    "+++ b/python/sglang/srt/managers/scheduler.py\n"
    "@@ -23,6 +23,8 @@\n"
    " import time\n"
    " from array import array\n"
    " from collections import deque\n"
    "+from concurrent.futures import ThreadPoolExecutor\n"
    "+from contextvars import copy_context\n"
    " from contextlib import contextmanager, nullcontext\n"
    " from functools import partial\n"
    " from http import HTTPStatus\n"
    "@@ -2124,6 +2126,7 @@\n"
    "                 else:\n"
    "                     self.ipc_channels.send_to_tokenizer.send_output(output, recv_req)\n"
    " \n"
    "+        self._poll_lora_prepares()\n"
    "         self.flush_wrapper.check_pending()\n"
    "         if self.external_corpus_manager is not None:\n"
    "             self.external_corpus_manager.check_pending_load()\n"
    "@@ -5650,8 +5653,66 @@\n"
    "     ) -> LoadLoRAAdapterReqOutput:\n"
    '         """In-place loading a new lora adapter from disk or huggingface."""\n'
    " \n"
    "-        result = self.tp_worker.load_lora_adapter(recv_req)\n"
    "-        return result\n"
    "+        if (\n"
    '+            os.environ.get("SPINDLE_GLM_ASYNC_LORA_LOADING") != "1"\n'
    "+            or get_parallel().pp_size != 1\n"
    "+            or get_parallel().attn_dp_enabled\n"
    "+        ):\n"
    "+            return self.tp_worker.load_lora_adapter(recv_req)\n"
    '+        if not hasattr(self, "_lora_prepare_executor"):\n'
    "+            self._lora_prepare_executor = ThreadPoolExecutor(\n"
    '+                max_workers=1, thread_name_prefix="lora-prepare"\n'
    "+            )\n"
    "+            self._pending_lora_prepares = deque()\n"
    "+            self._cancelled_lora_prepares = set()\n"
    "+        manager = self.tp_worker.model_runner.lora_manager\n"
    "+        future = self._lora_prepare_executor.submit(\n"
    "+            copy_context().run, manager.prepare_lora_adapter, recv_req.to_ref()\n"
    "+        )\n"
    "+        self._pending_lora_prepares.append((recv_req, future, time.monotonic()))\n"
    "+        return None\n"
    "+\n"
    "+    def _poll_lora_prepares(self):\n"
    '+        pending = getattr(self, "_pending_lora_prepares", None)\n'
    "+        if not pending:\n"
    "+            return\n"
    "+        request, future, started = pending[0]\n"
    '+        ready = torch.tensor([future.done()], dtype=torch.int32, device="cpu")\n'
    "+        distributed = torch.distributed.is_initialized()\n"
    "+        if distributed:\n"
    "+            torch.distributed.all_reduce(\n"
    "+                ready, op=torch.distributed.ReduceOp.MIN, group=self.tp_cpu_group\n"
    "+            )\n"
    "+        if not ready.item():\n"
    "+            return\n"
    "+        manager = self.tp_worker.model_runner.lora_manager\n"
    "+        ref = request.to_ref()\n"
    "+        error = None\n"
    "+        try:\n"
    "+            prepared = future.result()\n"
    "+            if ref.lora_id in self._cancelled_lora_prepares:\n"
    '+                raise RuntimeError("Adapter unloaded during preparation")\n'
    "+            manager.validate_new_adapter(prepared[0], ref)\n"
    "+        except Exception as exc:\n"
    '+            error = f"{type(exc).__name__}: {exc}"\n'
    "+        errors = [error]\n"
    "+        if distributed:\n"
    "+            errors = [None] * torch.distributed.get_world_size(self.tp_cpu_group)\n"
    "+            torch.distributed.all_gather_object(errors, error, group=self.tp_cpu_group)\n"
    "+        if any(errors):\n"
    "+            output = manager.create_lora_update_result(\n"
    '+                False, "; ".join(e for e in errors if e)\n'
    "+            )\n"
    "+        else:\n"
    "+            output = manager.install_prepared_lora_adapter(ref, prepared)\n"
    "+        pending.popleft()\n"
    "+        self._cancelled_lora_prepares.discard(ref.lora_id)\n"
    '+        logger.info("LoRA preparation completed id=%s seconds=%.3f success=%s",\n'
    "+                    ref.lora_id, time.monotonic() - started, output.success)\n"
    "+        if self.rust_server is not None:\n"
    "+            self.rust_server.push_control_output(request, output)\n"
    "+        else:\n"
    "+            self.ipc_channels.send_to_tokenizer.send_output(output, request)\n"
    " \n"
    "     def load_lora_adapter_from_tensors(\n"
    "         self, recv_req: LoadLoRAAdapterFromTensorsReqInput\n"
    "@@ -5666,8 +5727,11 @@\n"
    "     ) -> UnloadLoRAAdapterReqOutput:\n"
    '         """Unload the lora adapter."""\n'
    " \n"
    "-        result = self.tp_worker.unload_lora_adapter(recv_req)\n"
    "-        return result\n"
    '+        for request, future, _ in getattr(self, "_pending_lora_prepares", ()):\n'
    "+            if request.lora_id == recv_req.lora_id:\n"
    "+                self._cancelled_lora_prepares.add(request.lora_id)\n"
    "+                future.cancel()\n"
    "+        return self.tp_worker.unload_lora_adapter(recv_req)\n"
    " \n"
    "     def init_weights_send_group_for_remote_instance(\n"
    "         self, recv_req: InitWeightsSendGroupForRemoteInstanceReqInput\n"
    "@@ -5746,6 +5810,9 @@\n"
    "             self.session_controller.close(recv_req)\n"
    " \n"
    "     def maybe_sleep_on_idle(self):\n"
    '+        if getattr(self, "_pending_lora_prepares", None):\n'
    "+            time.sleep(0.005)\n"
    "+            return\n"
    "         if self.idle_sleeper is not None:\n"
    "             self.idle_sleeper.maybe_sleep()\n"
    " \n"
    "@@ -5757,6 +5824,9 @@\n"
    " \n"
    "     def handle_shutdown(self, recv_req: ShutdownReq):\n"
    "         # Break the event loop; the finally in run_scheduler_process releases resources.\n"
    '+        executor = getattr(self, "_lora_prepare_executor", None)\n'
    "+        if executor is not None:\n"
    "+            executor.shutdown(wait=False, cancel_futures=True)\n"
    "         self.gracefully_exit = True\n"
    "         return None\n"
    " \n"
)
